class StochasticRng:
    def __init__(self, seed: int | None = None) -> None: ...
    def normal(self) -> float: ...
    def normals(self, n: int) -> list[float]: ...
    def uniform(self) -> float: ...
    def get_seed(self) -> int | None: ...

class BrownianMotion:
    def __init__(self, time_horizon: float, num_steps: int) -> None: ...
    def generate_path(self) -> list[float]: ...
    def generate_paths(self, num_paths: int) -> list[list[float]]: ...
    def generate_paths_parallel(self, num_paths: int) -> list[list[float]]: ...
    def time_grid(self) -> list[float]: ...
    def dt(self) -> float: ...
    def get_time_horizon(self) -> float: ...
    def get_num_steps(self) -> int: ...
    def generate_antithetic_paths(self) -> tuple[list[float], list[float]]: ...

class GeometricBrownianMotion:
    def __init__(
        self,
        spot: float,
        drift: float,
        volatility: float,
        time_horizon: float,
        num_steps: int,
    ) -> None: ...
    def generate_path(self) -> list[float]: ...
    def generate_paths(self, num_paths: int) -> list[list[float]]: ...
    def generate_paths_parallel(self, num_paths: int) -> list[list[float]]: ...
    def time_grid(self) -> list[float]: ...
    def dt(self) -> float: ...
    def generate_antithetic_paths(self) -> tuple[list[float], list[float]]: ...
    def terminal_prices(self, num_paths: int) -> list[float]: ...
    def get_spot(self) -> float: ...
    def get_drift(self) -> float: ...
    def get_volatility(self) -> float: ...
    def get_time_horizon(self) -> float: ...
    def get_num_steps(self) -> int: ...

class HestonProcess:
    def __init__(
        self,
        spot: float,
        initial_variance: float,
        drift: float,
        kappa: float,
        theta: float,
        vol_of_vol: float,
        correlation: float,
        time_horizon: float,
        num_steps: int,
    ) -> None: ...
    def generate_path(self) -> tuple[list[float], list[float]]: ...
    def generate_paths(self, num_paths: int) -> list[tuple[list[float], list[float]]]: ...
    def generate_paths_parallel(self, num_paths: int) -> list[tuple[list[float], list[float]]]: ...
    def time_grid(self) -> list[float]: ...
    def dt(self) -> float: ...
    def terminal_prices(self, num_paths: int) -> list[float]: ...
    def terminal_values(self, num_paths: int) -> tuple[list[float], list[float]]: ...
    def get_spot(self) -> float: ...
    def get_initial_variance(self) -> float: ...
    def get_drift(self) -> float: ...
    def get_kappa(self) -> float: ...
    def get_theta(self) -> float: ...
    def get_vol_of_vol(self) -> float: ...
    def get_correlation(self) -> float: ...
    def get_time_horizon(self) -> float: ...
    def get_num_steps(self) -> int: ...
