class Security:
    maturity: float
    price: float
    face_value: float
    coupon_rate: float
    frequency: int

    def __init__(
        self,
        maturity: float,
        price: float,
        face_value: float = 100.0,
        coupon_rate: float = 0.0,
        frequency: int = 0,
    ) -> None: ...
    def is_zero_coupon(self) -> bool: ...

class ZeroCouponCurve:
    securities: list[Security]

    def __init__(self, securities: list[Security], interpolation: str | None = None) -> None: ...
    def discount_factor(self, maturity: float) -> float: ...
    def get_interpolation_method(self) -> str: ...
    def zero_rate(self, maturity: float) -> float: ...
    def maturities(self) -> list[float]: ...
    def zero_rates(self) -> list[float]: ...
    def discount_factors(self) -> list[float]: ...
    def present_value(self, cash_flow: float, maturity: float) -> float: ...
    def present_value_many(self, cash_flows: list[float], maturities: list[float]) -> float: ...
    def add_security(self, security: Security) -> None: ...
    def size(self) -> int: ...
    @staticmethod
    def from_vectors(
        maturities: list[float],
        prices: list[float],
        face_values: list[float] | None = None,
        interpolation: str | None = None,
    ) -> ZeroCouponCurve: ...
    @staticmethod
    def discount_factors_many(curve: ZeroCouponCurve, maturities: list[float]) -> list[float]: ...
    @staticmethod
    def zero_rates_many(curve: ZeroCouponCurve, maturities: list[float]) -> list[float]: ...

class ForwardCurve:
    base_curve: ZeroCouponCurve

    def __init__(self, base_curve: ZeroCouponCurve) -> None: ...
    def instantaneous_forward_rate(self, t: float, dt: float | None = None) -> float: ...
    def forward_rate(self, t1: float, t2: float) -> float: ...
    def forward_rates_many(
        self,
        start_times: list[float],
        end_times: list[float],
    ) -> list[float]: ...
    def term_structure(
        self,
        start: float,
        end: float,
        step: float,
    ) -> tuple[list[float], list[float]]: ...
    def forward_discount_factor(self, t1: float, t2: float) -> float: ...
    def forward_bond_price(
        self,
        t1: float,
        t2: float,
        face_value: float | None = None,
    ) -> float: ...
    def get_base_curve(self) -> ZeroCouponCurve: ...

class InterpolationMethod:
    Linear: InterpolationMethod
    LogLinear: InterpolationMethod
    CubicSpline: InterpolationMethod

__all__ = ["ForwardCurve", "InterpolationMethod", "Security", "ZeroCouponCurve"]
